name: Next.js

on:
  pull_request:
  push:
    branches:
      - main
      - next
permissions:
  contents: read
env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093
        with: cache

      - name: Install Dependencies
        run: pnpm ci

      - name: Build with Next.js
        run: pnpm run build
